# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ab2af19fb92e05914140c0a8899b481ffd7ea1db52ab4c56727fb61259efa241a243a8da6a541f36914d784b1d5fb11f968d8fbda4681e616fea7e33decb3f

test:
  secret_key_base: d0d16e18cc649bf3142b3cba06bf29fac59939c844b32c208739654d233c21bbf43bb2d8ff153dd266e521267b9c38e08339d9ba49a642b09fd92b19453d675b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
